import React from 'react'
import Head from 'next/head'

export default function Header() {
  return (
    <>
        <Head>
        <title>Delta AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Rubik+Marker+Hatch&display=swap" rel="stylesheet"/>

        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
    </>
  )
}
